(define (numeros num1 num2)
	(clear)
	(define t1 (string-search-forward "." num1))
	(define t2 (string-search-forward "." num2))
	(define p1 (string-length num1))
	(define p2 (string-length num2))
	; (define r1 (- p1 t1))
	; (define r2 (- p2 t2))
	; (display r1)(newline)
	; (display r2)(newline)
	(if (> r1 r2)
		(display num1)
		(if (= r1 r2)
			(display "Los dos son iguales")
			(display num2)
		)
	)
)